[icons]
# font awesome
#TelegramDesktop = ""
firefox = ""
Alacritty = ""
discord = ""
obsidian = ""
#Thunderbird = ""
#Nautilus = "📘"

[aliases]
"firefox.*" = "firefox"
#TelegramDesktop = "Telegram"
#"Org\\.gnome\\.Nautilus" = "Nautilus"

[general]
separator = " | "
#default_icon = ""
wm_property = "class"

[options]
remove_duplicates = false
no_names = false
no_icon_names = true
